version: '3.7'

services:
  app:
    build:
      context: .
    env_file:
     - .env
    ports:
    - 8080:8080
    depends_on:
      - db
    command: >
      sh -c "gunicorn app.main:app --workers 8 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080"

  db:
    image: postgres:13
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ../redis_data:/data
    ports:
      - "6379:6379"

